server:
  port: 9090
  tomcat:
    threads:
      # 最大工作线程数，默认200, 4核8g内存，线程数经验值800
      max: 800
      # 最小工作空闲线程数，默认10, 适当增大一些，以便应对突然增长的访问量
      min-spare: 100
    # 等待队列长度，默认100
    accept-count: 1000
    max-connections: 20000

spring:
  application:
    name: project-demo

logging:
  file:
    path: ./log

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)